import { createServerClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';
import { NextRequest, NextResponse } from 'next/server';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import ReactPDF from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#000',
    paddingBottom: 10,
  },
  name: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  contact: {
    fontSize: 10,
    color: '#666',
    marginBottom: 3,
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 8,
    marginTop: 10,
  },
  text: {
    fontSize: 11,
    marginBottom: 4,
    color: '#333',
  },
  jobTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 4,
  },
});

export async function POST(request: NextRequest) {
  try {
    // Get authenticated user
    const cookieStore = cookies();
    const supabase = createServerClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!,
      {
        cookies: {
          getAll() {
            return cookieStore.getAll();
          },
          setAll(cookiesToSet) {
            try {
              cookiesToSet.forEach(({ name, value, options }) => {
                cookieStore.set(name, value, options);
              });
            } catch (error) {
              console.error('Cookie setting error:', error);
            }
          },
        },
      }
    );

    const {
      data: { session },
    } = await supabase.auth.getSession();

    if (!session?.user) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    // Get job_id from request body
    const body = await request.json();
    const { job_id } = body;

    if (!job_id) {
      return NextResponse.json(
        { error: 'Job ID is required' },
        { status: 400 }
      );
    }

    // Fetch job and profile
    const { data: job, error: jobError } = await supabase
      .from('jobs')
      .select('*')
      .eq('job_id', job_id)
      .single();

    if (jobError || !job) {
      return NextResponse.json(
        { error: 'Job not found' },
        { status: 404 }
      );
    }

    const { data: profile, error: profileError } = await supabase
      .from('profiles')
      .select('*')
      .eq('id', session.user.id)
      .single();

    if (profileError || !profile) {
      return NextResponse.json(
        { error: 'Profile not found' },
        { status: 404 }
      );
    }

    // Generate PDF
    const CVDocument = (
      <Document>
        <Page size="A4" style={styles.page}>
          {/* Header */}
          <View style={styles.header}>
            <Text style={styles.name}>{profile.full_name}</Text>
            <Text style={styles.contact}>{profile.email}</Text>
            <Text style={styles.contact}>{profile.location}</Text>
          </View>

          {/* Target Role */}
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Target Position</Text>
            <Text style={styles.jobTitle}>{job.role}</Text>
            <Text style={styles.text}>{job.company}</Text>
          </View>

          {/* Profile Summary */}
          {profile.profile_summary && (
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>Professional Summary</Text>
              <Text style={styles.text}>{profile.profile_summary}</Text>
            </View>
          )}

          {/* Job Preference */}
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Job Preference</Text>
            <Text style={styles.text}>{profile.job_preference}</Text>
          </View>

          {/* Skills */}
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Skills</Text>
            {job.tags && job.tags.length > 0 ? (
              <View>
                {job.tags.map((tag: string, idx: number) => (
                  <Text key={idx} style={styles.text}>
                    • {tag}
                  </Text>
                ))}
              </View>
            ) : (
              <Text style={styles.text}>
                Skills matching this position
              </Text>
            )}
          </View>

          {/* Footer */}
          <View
            style={{
              marginTop: 30,
              paddingTop: 10,
              borderTopWidth: 1,
              borderTopColor: '#000',
            }}
          >
            <Text style={{ fontSize: 9, color: '#999' }}>
              Generated by CareerAI for {job.company}
            </Text>
          </View>
        </Page>
      </Document>
    );

    // Render PDF to bytes
    const pdfBytes = await ReactPDF.pdf(CVDocument).toBuffer();

    // Return PDF
    return new NextResponse(pdfBytes, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="cv-${job.company.replace(/\s+/g, '-')}-${job.role.replace(/\s+/g, '-')}.pdf"`,
      },
    });
  } catch (error) {
    console.error('PDF generation error:', error);
    return NextResponse.json(
      { error: 'Failed to generate PDF' },
      { status: 500 }
    );
  }
}
